# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnvr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnvr
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'

  target 'rnvrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnvr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnvr-tvOS

  target 'rnvr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
