export const SET_SPEECH_START = 'SET_SPEECH_START';
export const SET_SPEECH_RECOGNIZED = 'SET_SPEECH_RECOGNIZED';
export const SET_SPEECH_RESULTS = 'SET_SPEECH_RESULTS';
export const START_RECOGNITION = 'START_RECOGNITION';
export const SET_RECORDING = 'SET_RECORDING';
